services:
  - type: web
    name: attestflow-indexer
    env: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install && pnpm --filter @attestflow/sdk build && pnpm --filter @attestflow/indexer build
    startCommand: pnpm --filter @attestflow/indexer start
    envVars:
      - key: PORT
        value: '3001'
      - key: RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: ATTESTER_ID
        value: CB4B22G5BMGCQQTH3MPNFF4MGLH342OP7PBLBBVK2XY3LCVSMYK4WPDO
      - key: SCHEMA_REGISTRY_ID
        value: CC4UT6NXLX7GP33XOKQKHQZTN3TTUQ3MCHVOD77U5EMH2FPRXACYY6JH
